### ISSUE TITLE
Python 3.5.3? 

### ISSUE THREAD

**Issue by radames** [DeftWork/rpi-tensorflow#1]
The new Raspbian Stretch comes with Python 3.5.3, are you planning to compile tf for py35?

**Comment by DeftWork** [comment]
I'm sorry, but not in the short term.

**Comment by DeftWork** [comment]
I hope it can help you:

https://github.com/DeftWork/rpi-tensorflow-py3
https://hub.docker.com/r/elswork/rpi-tensorflow-py3/

**Comment by radames** [comment]
this looks good! thanks for the work
