### ISSUE TITLE
Tensorflow 1.4.1 support

### ISSUE THREAD

**Issue by yellowiscool** [DeftWork/rpi-tensorflow#2]
Hei, thanks for sharing this docker image. It has saved me a lot of time.

I would like to know whether you plan to support tensorflow 1.4.1

**Comment by DeftWork** [comment]
Thanks, I've tried to compile binaries without success, I'll probably try again in the future, but I can not promise anything, I'm sorry.

**Comment by DeftWork** [comment]
I've found Tensorflow binaries for raspberry but I've not tested yet:
[tensorflow-1.4.0-cp27-none-any.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi/lastSuccessfulBuild/artifact/output-artifacts/tensorflow-1.4.0-cp27-none-any.whl)
[tensorflow-1.4.0-cp34-none-any.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/lastSuccessfulBuild/artifact/output-artifacts/tensorflow-1.4.0-cp34-none-any.whl)
